### PR TITLE
Add Visual Preview

### PR DESCRIPTION
**Pull request by Dzakus**
Visual Preview for Bar Height, Volume Panel Alpha
Update Settings for Bar Height without reboot SystemUI
Hide launcher shortcut
Use int to store digital value instead of String (SharedPreference)
preference xml code cleanup and many other cleanup
+many other

### CODE REVIEW

**Comment by Dzakus** [comment]
@Zst123 look at this. Working good. I'm go to sleep now.

**Comment by Dzakus** [comment]
Sorry for submit my classpath.

**Comment by zst123** [comment]
I'll edit it. Thanks very much for the live previews for the batterybar/volume panel. I'll take a look at it

**Comment by Dzakus** [comment]
Do you planning a new features? I can help

**Comment by zst123** [comment]
Thanks a lot for the broadcast implantation. I was researching on how to do it. No plans to do anything yet.. Other than the xda premium 4/tapatalk listview animation bug where all views will show animation every time it is scrolled.

**Comment by Dzakus** [comment]
Disable per app? Or disable per Activity?

**Pull request closed without merging**
