### PR TITLE
Add "Always Show Scrollbars" feature

### PR DESCRIPTION
**Pull request by elevengu**

### CODE REVIEW

**Comment by zst123** [comment]
Thanks. Did you test it? Apparently it has no effect at all

**Comment by zst123** [comment]
I got it working after a few modifications.

```
private static void hookScrollbarNoFading(final Class<?> clazz) {
        XposedBridge.hookAllConstructors(View.class, new XC_MethodHook() {
            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                if (!(param.thisObject instanceof ScrollView) &&
                        !(param.thisObject instanceof ListView)) {
                        // If we set scrollbar for non-scrollable views, we will bootloop
                        return;
                }

                if (!isEnabled()) return;
                if (!mPref.getBoolean(Common.KEY_SCROLLING_NO_FADING,
                        Common.DEFAULT_SCROLLING_NO_FADING)) return;


                ((View) param.thisObject).setScrollbarFadingEnabled(false);
            }
        });

    }
```

**Comment by elevengu** [comment]
Thanks, I've made the changes.

**Comment by zst123** [comment]
Thanks. I have combined it into a single commit and merged it
https://github.com/zst123/XuiMod/commit/f447273d832b9ece78633eef95f4721d22907522

**Pull request closed without merging**
